#       Cursor
env = HYPRCURSOR_THEME,Bibata-Modern-Classic
env = HYPRCURSOR_SIZE,22
env = WLR_NO_HARDWARE_CURSORS,1

#       Wayland / Toolkit behavior
env = ELECTRON_OZONE_PLATFORM_HINT,auto
env = QT_QPA_PLATFORM, wayland

#        Theme integration
env = QT_QPA_PLATFORMTHEME, qt5ct
env = GTK_THEME, adw-gtk3-dark

#        Desktop identity
env = XDG_CURRENT_DESKTOP, Hyprland
env = XDG_SESSION_TYPE, wayland

#        Terminal
env = TERMINAL,kitty -1

#        Applications
env = XDG_DATA_DIRS,$HOME/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share

#       Intel gpu fix
env = LIBVA_DRIVER_NAME,iHD
env = VDPAU_DRIVER,va_gl
